name: Build LaTeX PDF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile with XeLaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      - name: Commit and Push PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          git add -f main.pdf
          git commit -m "chore: update compiled PDF [skip ci]" || echo "No changes to commit"
          git push origin main
          echo Add other actions to build,
          echo test, and deploy your project.
